---
title: "In-class Exercise 10a: Dashboard Design Using Quarto"
format: 
  dashboard:
    orientation: columns
date: "June 22, 2024"
date-modified: "last-modified"
execute:
  eval: true
  echo: false
  warning: false
  freeze: true
---

## Loading the R Package

```{r}
pacman::p_load(lubridate, ggthemes, reactable,
               reactablefmtr, gt, gtExtras, tidyverse)
```

## Loading the Data

```{r}
coffeechain <- read_rds("data/rds/CoffeeChain.rds")
```

## Product Sales

```{r}
productSales <- coffeechain %>%
  group_by(Product) %>%
  summarise(`target` = sum(`Budget Sales`),
            `current` = sum(`Sales`)) %>%
  ungroup()
```

## Product Profit

```{r}
productProfit <- coffeechain %>%
  group_by(Product) %>%
  summarise(`target` = sum(`Budget Profit`),
            `current` = sum(`Profit`)) %>%
  ungroup()
```

## Column {width = 50%}

```{r}
#| title: Sales by Products
ggplot(productSales, aes(Product, current)) +
  geom_col(aes(Product, max(target) * 1.01),
           fill = "grey85", width = 0.85) +
  geom_col(aes(Product, target * 0.75),
           fill = "grey60", width = 0.85) +
  geom_col(aes(Product, target * 0.5),
           fill=  "grey50", width = 0.85) +
  geom_col(aes(Product, current),
           width = 0.35,
           fill = "black") +
  geom_errorbar(aes(y = target,
                    x = Product,
                    ymin = target,
                    ymax = target),
                width = .4,
                colour = "red",
                size = 1) +
  coord_flip()
```

## Column {width = 50%}

```{r}
#| title: Profit by Products
ggplot(productProfit, aes(Product, current)) +
  geom_col(aes(Product, max(target) * 1.01),
           fill = "grey85", width = 0.85) +
  geom_col(aes(Product, target * 0.75),
           fill = "grey60", width = 0.85) +
  geom_col(aes(Product, target * 0.5),
           fill=  "grey50", width = 0.85) +
  geom_col(aes(Product, current),
           width = 0.35,
           fill = "black") +
  geom_errorbar(aes(y = target,
                    x = Product,
                    ymin = target,
                    ymax = target),
                width = .4,
                colour = "red",
                size = 1) +
  coord_flip()
```





